services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net
  
  kube_news:
    image: josefabiorosa/kube-news:${KUBE_NEWS_TAG:-latest}
    ports: 
      - 8080:8080
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgre
    depends_on:
      - postgre
    networks:
      - kube_news_net

include:
  - ./nginx.compose.yaml

volumes:
  postgre_docker_vol:
    name: postgre_exemplo_vol
    external: true

networks:
  kube_news_net:
    driver: bridge