apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-postgresql
data:
  POSTGRES_PASSWORD: "Pg#123"
  POSTGRES_USER: "kubenews"
  POSTGRES_DB: "kubenews"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kubenews
data:
  DB_DATABASE: "kubenews"
  DB_USERNAME: "kubenews"
  DB_PASSWORD: "Pg#123"
  DB_HOST: "postgresql"