apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-postgresql
                key: POSTGRES_PASSWORD_VALOR
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-postgresql
                key: POSTGRES_USER_VALOR
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: secret-postgresql
                key: POSTGRES_DB_VALOR
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: josefabiorosa/aula-kube-news:v1
        ports:
        - containerPort: 8080
        env:
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: secret-kubenews
                key: DB_DATABASE_VALOR
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-kubenews
                key: DB_USERNAME_VALOR
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-kubenews
                key: DB_PASSWORD_VALOR
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: secret-kubenews
                key: DB_HOST_VALOR      
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort